#pragma once

enum class GameState {


    MAIN_MENU,CHARACTER_SELECT,PLAYING,PAUSED,GAME_OVER,LEVEL_COMPLETE,BOSS_DEFEATED,SHOP,LOGIN,LEADERBOARD,TRAILER,STAR_EVENT
    
    };
    
    //1-MAIN_MENU   X
    //2-CHARACTER_SELECT
    //3-PLAYING.   X
    //4-PAUSED    x
    //5-GAME_OVER   x
    //6-LEVEL_COMPLETE
    //7-BOSS_DEFEATED
    //8-SHOP        X
    //9-LOGIN       
    //10-LEADERBOARD x  
    //11-TRAILER
    //12-LEVEL_UP   

    //13-STAR_EVENT X
    //14-RAIN_EVENT
